# Generated by Django 6.1 on 2026-08-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='memories/')),
                ('caption', models.CharField(max_length=200)),
                ('date_label', models.CharField(blank=True, help_text="Free text, e.g. 'Summer 2021' or 'The day we met'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('message', models.TextField(max_length=500)),
                ('color', models.CharField(choices=[('pink', 'Pink'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('purple', 'Purple')], default='pink', help_text='Sticky-note color on the wall.', max_length=20)),
                ('approved', models.BooleanField(default=True, help_text='Uncheck to hide a message without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(default='Friend', help_text="Shown in the big hero headline, e.g. 'Priya'.", max_length=100)),
                ('hero_tagline', models.CharField(blank=True, default='Press the button. Things will happen.', help_text='Small line under the headline.', max_length=200)),
                ('letter_title', models.CharField(default='A letter for you', max_length=150)),
                ('letter_body', models.TextField(blank=True, help_text='Your birthday letter. Line breaks are preserved.')),
                ('spotify_embed_url', models.URLField(blank=True, help_text='Paste a Spotify EMBED url, e.g. https://open.spotify.com/embed/playlist/XXXXXXXX. In Spotify: Share -> Embed playlist -> copy the src="..." link.')),
            ],
            options={
                'verbose_name': 'Site config',
                'verbose_name_plural': 'Site config (edit the one row)',
            },
        ),
    ]
